name: Tests
on: [push, pull_request]
env:
  CODE_COVERAGE_THRESHOLD_REQUIRED: 75
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install flake8 pycodestyle bandit
      - name: Check syntax
        run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
      - name: Run flake8
        run: flake8 . --count --max-line-length=127 --statistics --exclude ckan
      - name: Run bandit
        run: bandit -s B101  -r ./ckanext/dq_assistant -f screen

  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: [2.9]
      fail-fast: false
    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-20.04
    container:
      image: ckan/ckan-dev:2.9-py3.9
      options: --user=root

    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}-solr9
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_INI: /__w/ckanext-ai-assistants/ckanext-ai-assistants/test.ini
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: | 
          pip install --upgrade setuptools==70.0.0 
          pip install --ignore-installed -r dev-requirements.txt
          pip install --ignore-installed -r requirements.txt
          pip install --editable .
          pip install --upgrade PyYAML==6.0.2
          pip install --upgrade webassets==2.0.0 
          pip freeze
          ls -la 
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
          
          # Install ckanext-xloader
          git clone --branch 0.12.2-opengov https://github.com/OpenGov-OpenData/ckanext-xloader
          pip install -r ckanext-xloader/requirements.txt
          pip install -e ckanext-xloader
      - name: Setup db
        run: ckan db init
      - name: Run tests
        run: pytest --cov=ckanext.dq_assistant --disable-warnings --cov-fail-under=${CODE_COVERAGE_THRESHOLD_REQUIRED} ckanext/dq_assistant/tests
